feat(limits): propagate generate limits
IBM/ibm-generative-ai pull request #184
Opened 2023-10-04 15:34 UTC by Tomas2D

---
## Status
**READY**

## Description

`generate_async` now orchestrates the generation tasks by syncing its limits state with the API rather than having a hard-coded value. Also, the graceful shutdown of the app should be faster as there will be fewer pending tasks.

## Impacted Areas in Library
Model - `generate_async` method

## Which issue(s) does this pull-request fix?
Closes: #147

## Any special notes for your reviewer?

Sleep timeouts - still not sure about ideal values (sleep and caching)

---

## Checklist
- [ ] Automated tests exist
- [ ] Updated Package Requirements (if required, and with maintainers' approval)
- [ ] Local unit tests performed
- [ ] Documentation exists [link]()
- [ ] Local pre-commit hooks performed
- [ ] Desired commit message set as PR title and description set above
- [ ] Link to relevant GitHub issue provided

2023-10-06 12:46 UTC, David-Kristek requested changes

2023-10-06 12:46 UTC, David-Kristek commented on src/genai/model.py
> +                    print("Helloo")
```suggestion
```

2023-10-06 12:46 UTC, David-Kristek commented on examples/user/async_greetings.py
> +    # throw_on_error=True,
Is the comment wanted?

2023-10-06 12:47 UTC, David-Kristek requested changes

2023-10-06 12:47 UTC, David-Kristek commented on src/genai/services/async_generator.py
> +            limits = self.service.generate_limits()
I think that this function should be mocked in testing in test_concurrent.py. - test is failing

2023-10-08 08:43 UTC, Tomas2D commented on src/genai/extensions/langchain/llm.py
> +        )
This part has been updated in a newer version of LangChain, but we want to support the old behaviour.

2023-10-09 15:56 UTC, David-Kristek approved these changes

2023-10-10 08:12 UTC, merged