fix: remove some typing errors
IBM/ibm-generative-ai pull request #193
Opened 2023-10-12 18:15 UTC by David-Kristek

Refs #191

---
## Status
**READY**

## Description

## Impacted Areas in Library

## Which issue(s) does this pull-request fix?

## Any special notes for your reviewer?

---

## Checklist
- [ ] Automated tests exist
- [ ] Updated Package Requirements (if required, and with maintainers' approval)
- [ ] Local unit tests performed
- [ ] Documentation exists [link]()
- [ ] Local pre-commit hooks performed
- [ ] Desired commit message set as PR title and description set above
- [ ] Link to relevant GitHub issue provided

2023-10-12 18:16 UTC, David-Kristek commented on src/genai/schemas/descriptions.py
> -    SEARCH = "Filters the items to be returned based on their name."
Duplicate

2023-10-12 18:17 UTC, David-Kristek commented on src/genai/schemas/responses.py
> -    id: str
Duplicates

2023-10-12 19:11 UTC, Tomas2D requested changes
Great work so far!

Besides these small changes, I saw some try/catch blocks with non-explicit exceptions to catch.

```
        try:
            response = service._prompt_templating.update_prompt_templates(id=id, name=name, value=template)
            if response.status_code == 200:
                response_result = WatsonxTemplate(**response.json()["results"])
                return response_result
            raise GenAiException(response)
        except Exception as ex:
            raise GenAiException(ex)
```

This is firstly bad practice, but for now, it is sufficient to handle cases like this in the following way:

```
        except Exception as ex:
            raise to_genai_error(ex)
```

2023-10-12 19:11 UTC, Tomas2D commented on src/genai/extensions/pandas/prompt_sub.py
> +    ) -> list["PromptPattern"]:
This is probably not correct based on the implementation. Can you try it out?

2023-10-12 19:11 UTC, Tomas2D commented on src/genai/model.py
> +            throw_on_error(bool, optional): Throws error on failure.
You are missing a default value.

2023-10-12 19:11 UTC, Tomas2D commented on src/genai/services/tune_manager.py
> +    ) -> Union[TuneInfoResult, None]:
`Union[TuneInfoResult, None]` -> `Optional[TuneInfoResult]`

2023-10-15 19:34 UTC, David-Kristek commented on src/genai/prompt_pattern.py
> -        return complete_prompt
This didn't return the correct type - only arrays.

2023-10-16 06:37 UTC, Tomas2D requested changes

2023-10-16 06:37 UTC, Tomas2D commented on src/genai/services/async_generator.py
> +            raise to_genai_error(ex)
Could you keep it as is? We want the same error in the queue (line above) to be the same as the error we just raised.

2023-10-16 06:37 UTC, Tomas2D commented on tests/test_prompt_pattern.py
> +        assert isinstance(res, PromptPattern) is True
👍🏻

2023-10-16 18:53 UTC, Tomas2D approved these changes

2023-10-16 18:54 UTC, merged