feat: migrate to pydantic v2
IBM/ibm-generative-ai pull request #198
Opened 2023-10-17 14:24 UTC by Tomas2D

---
## Status
**READY**

## Description

Migrate to Pydantic v2

## Impacted Areas in Library
All

## Which issue(s) does this pull-request fix?
Closes: #67

---

## Checklist
- [ ] Automated tests exist
- [ ] Updated Package Requirements (if required, and with maintainers' approval)
- [ ] Local unit tests performed
- [ ] Documentation exists [link]()
- [ ] Local pre-commit hooks performed
- [ ] Desired commit message set as PR title and description set above
- [ ] Link to relevant GitHub issue provided

2023-10-19 13:28 UTC, David-Kristek requested changes
I found a few depracated things inside tests: 
Multiple times `parse_obj`:
https://github.com/Tomas2D/ibm-generative-ai/blob/dccf997a99f6eedb9075a2e510ea8bcc33e8a407/tests/test_prompt_template_manager.py

Other:
https://github.com/Tomas2D/ibm-generative-ai/blob/dccf997a99f6eedb9075a2e510ea8bcc33e8a407/tests/test_prompt_pattern_watsonx.py#L19-L20

https://github.com/Tomas2D/ibm-generative-ai/blob/dccf997a99f6eedb9075a2e510ea8bcc33e8a407/tests/test_request_handler.py#L17

2023-10-19 15:18 UTC, onkarbhardwaj commented
@Tomas2D , @David-Kristek: ibm-generative-ai could be used in applications for which there could exist dependencies which may not have been transitioned to pydantic>=2.0. I am wondering if this library should take care of such use cases.

It could possibly involve
- Removing version qualifiers
- Creating some kind of wrapper/class that returns appropriate object based on pydantic version installed

For example, `pydantic_utils.py` could contain

```python

def get_model(obj):
     if ... :# version < 2.0
         return obj.copy()
     else:
         return obj.model_copy()
```

By no means proposing a final solution but just starting a discussion if there exists a feasible path which could be taken up based on priorities.

2023-10-20 11:29 UTC, Tomas2D commented
Hey @onkarbhardwaj, thanks for sharing your attitude. I agree that this may break some projects; note that I considered that. We will either do the wrapper class (like you just mentioned) or do a breaking change with other changes once we release the 1.0.0 version (depending on the timespan).

2023-10-20 12:49 UTC, David-Kristek approved these changes

2023-10-24 11:52 UTC, merged