Retry strategy and use semaphores to prevent a large number of tasks …
IBM/ibm-generative-ai pull request #36
Opened 2023-06-14 18:22 UTC by onkarbhardwaj

---
## Status
**IN DEVELOPMENT**

## Description
- As a workaround for temporary network outages and temporary deployment issues, we are introducing backoff for asynchronous versions of `generate` and `tokenize`.
- We are also introducing semphores to prevent a large number of simultaneous async tasks getting created in case a user thinks of sending hundreds of thousands of prompts.
- Semaphores also enable Retry strategy in a subtle way by preventing pushing a request-to-be-retried behind a large number of async queries. If not prevented, such a query could potentially be pushed behind all these tasks and that would affect run-time for `ordered` mode of `generate_async`.
- Semaphores also enabled running much larger number of prompts in async manner.

## Impacted Areas in Library
`AsyncResponseGenerator`

## Which issue(s) does this pull-request fix?
Closes: #15 

## Any special notes for your reviewer?
For testing the effect of semaphores, try sending a large number of prompts (>200k) with or without these changes. The exact number might differ system-to-system. For retry-strategy, check the tests.
---

## Checklist
- [x] Automated tests exist
- [ ] Updated Package Requirements (if required, and with maintainers' approval)
- [x] Local unit tests performed
- [x] Documentation exists [link]()
- [x] Local pre-commit hooks performed
- [x] Desired commit message set as PR title and description set above
- [x] Link to relevant GitHub issue provided

2023-06-21 13:02 UTC, jpwsutton approved these changes

2023-06-23 15:03 UTC, mirianfsilva approved these changes
lgtm!

2023-06-23 20:10 UTC, onkarbhardwaj commented
Resolved merge conflict via GUI. Hope tabs don't create an indentation issue.

2023-06-27 20:24 UTC, moneill0 approved these changes

2023-06-27 21:15 UTC, mirianfsilva requested changes
tests are not passing after merge with develop. But the async examples works fine with +550 prompts.

2023-06-29 15:22 UTC, mirianfsilva commented on examples/dev/async-flaky-request-handler.py
> +            parameters (dict, optional): Key-value pairs for model parameters. Defaults to None.
```suggestion
            parameters (dict, optional): Key-value pairs for model parameters. Defaults to None.
            options (Options, optional): Additional parameters to pass in the query payload. Defaults to None.
```

2023-06-30 17:33 UTC, merged